build_rich_readme:
  image: 
    name: pandoc/latex:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    # Example: Convert README.md to a professional PDF using the 'eisvogel' template style
    - pandoc README.md -o PE04_WS25-26_Report.pdf --pdf-engine=xelatex
  artifacts:
    paths:
      - PE04_WS25-26_Report.pdf
